-- Sprint B16-B17 - Add PASSWORD_RESET, TWO_FACTOR_ENABLED, TWO_FACTOR_DISABLED to ActionType enum.

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET';
EXCEPTION
  WHEN OTHERS THEN null;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'TWO_FACTOR_ENABLED';
EXCEPTION
  WHEN OTHERS THEN null;
END $$;

DO $$ BEGIN
  ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'TWO_FACTOR_DISABLED';
EXCEPTION
  WHEN OTHERS THEN null;
END $$;
