-- Sprint C2 - Add TICKET and TICKET_ATTACHMENT to ItemType enum.

DO $$ BEGIN
  ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'TICKET';
EXCEPTION
  WHEN OTHERS THEN null;
END $$;

DO $$ BEGIN
  ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'TICKET_ATTACHMENT';
EXCEPTION
  WHEN OTHERS THEN null;
END $$;
